/**:
  ros__parameters:
    publish_geometry_updates: True
    publish_planning_scene: True
    publish_robot_description: True
    publish_robot_description_semantic: True
    publish_state_updates: True
    publish_transforms_updates: True

    planning_scene_monitor_options:
      name: "planning_scene_monitor"
      robot_description: "robot_description"
      joint_states_topic: joint_states
      attached_collision_object_topic: "attached_collision_object"
      publish_planning_scene_topic: "planning_scene"
      monitored_planning_scene_topic: "monitored_planning_scene"
      wait_for_initial_state_timeout: 10.0
      enable_octomap_monitor: false
      collision_object_topic: "collision_object"
      planning_scene_world_topic: "planning_scene_world"