/**:
  ros__parameters:
  # MoveIt uses this configuration for controller management
    allow_trajectory_execution: True
    moveit_manage_controllers: False

    capabilities: " 
        pilz_industrial_motion_planner/MoveGroupSequenceService 
        pilz_industrial_motion_planner/MoveGroupSequenceAction
      "
    disable_capabilities: ""
    monitor_dynamics: False

    trajectory_execution:
      execution_duration_monitoring: false
      trajectory_duration_monitoring: false
      allowed_execution_duration_scaling: 0.0
      allowed_goal_duration_margin: 0.0
      allowed_start_tolerance: 0.01